import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import {
  ShieldCheck,
  CheckCircle,
  XCircle,
  Check,
  X,
  Download,
  AlertTriangle,
} from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { SiteHeader } from "@/components/uw/SiteHeader";

export const Route = createFileRoute("/guidelines")({
  head: () => ({
    meta: [
      { title: "Partner Guidelines — UW Partner Coach" },
      {
        name: "description",
        content:
          "What UW Partners can and cannot say to customers. Mandatory compliance guidelines covering income claims, savings claims and marketing materials.",
      },
      { property: "og:title", content: "Partner Guidelines — UW Partner Coach" },
      {
        property: "og:description",
        content:
          "Approved and prohibited statements for UW Partners, plus compliance rules on income, savings and marketing claims.",
      },
    ],
  }),
  component: GuidelinesPage,
});

const approved = [
  "UW lets you bundle your energy, broadband, mobile and insurance with one provider.",
  "You'll get one app and one bill for all the services you take with UW.",
  "I can give you a personalised quote based on your current bills.",
  "UW offers a Price Pledge on energy for eligible bundled customers.",
  "Most customers who switch see a saving when they bundle their services.",
  "UW is regulated by Ofgem, Ofcom and the FCA where applicable.",
  "You can cancel anytime, subject to your contract terms.",
];

const prohibited = [
  {
    text: "You'll definitely save £500 a year with UW.",
    reason: "Specific unverified savings claims cannot be guaranteed for every customer.",
  },
  {
    text: "Everyone who joins UW ends up saving money.",
    reason: "Universal guarantees are misleading — savings depend on individual circumstances.",
  },
  {
    text: "You could easily earn £5,000 a month as a Partner.",
    reason: "Income promises are prohibited — earnings vary and are not guaranteed.",
  },
  {
    text: "We're definitely cheaper than British Gas / EE / Sky.",
    reason: "Unverified comparisons against named competitors are not permitted.",
  },
  {
    text: "You need to sign up today or you'll miss out forever.",
    reason: "Pressure tactics and false urgency are against our sales standards.",
  },
  {
    text: "Other providers are ripping you off / are worse than us.",
    reason: "Disparaging competitors is not permitted in any customer conversation.",
  },
  {
    text: "This is the best deal you'll ever find, no exceptions.",
    reason: "Absolute statements cannot be substantiated and may mislead customers.",
  },
];

const accordionSections = [
  {
    value: "income",
    title: "Income Claims",
    why: "Why it matters: the FCA and ASA require that earnings claims are fair, clear and not misleading. Promising specific income levels can constitute a financial promotion breach.",
    rules: [
      "Never state or imply a guaranteed income figure.",
      "Never compare your own earnings as a 'typical' outcome for new Partners.",
      "Do not promise earnings timelines (e.g. 'you'll be earning within a month').",
      "Always direct earnings questions to the official commission plan documentation.",
    ],
    instead: [
      "\"Earnings depend on the customers you sign up and vary from Partner to Partner.\"",
      "\"I can show you exactly how the commission plan works so you can see it for yourself.\"",
    ],
    script:
      "\"Everyone's results are different, but I'm happy to walk you through exactly how commission is calculated so you can decide if it's right for you.\"",
  },
  {
    value: "savings",
    title: "Savings Claims",
    why: "Why it matters: energy and broadband savings claims are closely regulated by Ofgem and Ofcom — unverified figures can mislead customers and breach advertising standards.",
    rules: [
      "Only quote savings figures generated by an official personalised quote tool.",
      "Never state a fixed savings amount before running a quote.",
      "Avoid words like 'guaranteed' or 'always' when discussing savings.",
      "Make clear that savings depend on current tariffs and usage.",
    ],
    instead: [
      "\"Let's run a personalised quote so you can see exactly what you'd pay.\"",
      "\"Many customers do save when they bundle, but it depends on your current deals.\"",
    ],
    script:
      "\"I can't promise a figure until I've seen your current bills, but let's get you a personalised quote so you know exactly where you stand.\"",
  },
  {
    value: "product",
    title: "Product Claims",
    why: "Why it matters: product and service claims must accurately reflect what UW actually offers, per Ofcom and Ofgem product marketing rules.",
    rules: [
      "Only describe features and services that are currently live and available in the customer's area.",
      "Don't promise future features or roadmap items as if they exist today.",
      "Be accurate about contract lengths, exit fees and coverage.",
      "Refer technical or coverage questions to official UW resources if unsure.",
    ],
    instead: [
      "\"UW bundles energy, broadband, mobile and insurance under one account.\"",
      "\"Let me check availability and contract terms for your postcode before we go further.\"",
    ],
    script:
      "\"I want to make sure I give you accurate information, so let me confirm availability for your address before we talk numbers.\"",
  },
  {
    value: "social",
    title: "Social Proof & Testimonials",
    why: "Why it matters: the ASA requires that testimonials used in sales conversations are genuine, current and not cherry-picked to imply typical results.",
    rules: [
      "Only share testimonials that are real, attributed and approved for use.",
      "Never imply a single testimonial represents a 'typical' customer outcome.",
      "Do not fabricate or exaggerate a customer story.",
      "Avoid using other Partners' private earnings stories without consent.",
    ],
    instead: [
      "\"One customer I helped saved by bundling their energy and broadband — results vary.\"",
      "\"Here's some feedback from Partners about what training was like for them.\"",
    ],
    script:
      "\"I can share a couple of real examples, but keep in mind everyone's situation is a bit different.\"",
  },
  {
    value: "marketing",
    title: "Marketing Materials",
    why: "Why it matters: only compliance-approved materials may be used with customers to ensure consistent, accurate and regulator-approved messaging.",
    rules: [
      "Only use flyers, scripts and social posts issued or approved by UW Compliance.",
      "Never edit approved materials or create your own without sign-off.",
      "Do not post customer testimonials or savings figures on personal social media without approval.",
      "Always include required disclaimers on printed or digital materials.",
    ],
    instead: [
      "\"I'll use the official UW brochure to walk you through this.\"",
      "\"Let me check compliance-approved wording before I send that over.\"",
    ],
    script:
      "\"I always use our official materials so you're getting accurate, up-to-date information.\"",
  },
  {
    value: "consequences",
    title: "Compliance Consequences",
    why: "Why it matters: breaches of these guidelines put customers, the UW brand and your Partnership at risk, and may trigger regulatory action.",
    rules: [
      "First breach: formal warning and mandatory retraining.",
      "Repeated breaches: suspension of Partner status pending investigation.",
      "Serious or deliberate misrepresentation: immediate termination of partnership.",
      "Customer complaints related to misrepresentation are reviewed by the Compliance team within 5 working days.",
    ],
    instead: [
      "\"If I'm ever unsure what I can say, I'll check with Compliance first.\"",
      "\"I always stick to approved statements even under pressure to close a sale.\"",
    ],
    script:
      "\"If you're ever unsure whether something is compliant, pause and check with compliance@uw.co.uk before saying it to a customer.\"",
  },
];

function GuidelinesPage() {
  const [bannerVisible, setBannerVisible] = useState(true);

  return (
    <div className="min-h-dvh bg-background">
      {bannerVisible && (
        <div className="sticky top-0 z-50 flex items-center justify-between gap-3 bg-brand px-4 py-3 text-primary-foreground sm:px-6">
          <p className="flex items-center gap-2 text-sm font-medium">
            <AlertTriangle className="size-4 shrink-0" aria-hidden="true" />
            ⚠️ These guidelines are mandatory. Violations may result in partnership termination.
          </p>
          <button
            type="button"
            onClick={() => setBannerVisible(false)}
            aria-label="Dismiss banner"
            className="grid size-8 shrink-0 place-items-center rounded-lg hover:bg-primary-foreground/10"
          >
            <X className="size-4" aria-hidden="true" />
          </button>
        </div>
      )}

      <SiteHeader />

      <main>
        {/* Hero */}
        <section className="bg-gradient-brand py-14 text-primary-foreground sm:py-20">
          <div className="mx-auto max-w-4xl px-4 text-center sm:px-6">
            <span className="mx-auto grid size-14 place-items-center rounded-2xl bg-primary-foreground/15">
              <ShieldCheck className="size-7" aria-hidden="true" />
            </span>
            <h1 className="mt-5 text-4xl font-bold tracking-tight text-balance">
              Partner Guidelines
            </h1>
            <p className="mt-3 text-base text-primary-foreground/85 sm:text-lg">
              What you can and cannot say as a UW Partner
            </p>
          </div>
        </section>

        {/* Comparison */}
        <section className="py-14 sm:py-20">
          <div className="mx-auto max-w-6xl px-4 sm:px-6">
            <div className="grid gap-8 lg:grid-cols-2">
              <div>
                <h2 className="flex items-center gap-2 text-xl font-bold">
                  <CheckCircle className="size-6 text-success" aria-hidden="true" />
                  Approved Statements
                </h2>
                <p className="mt-1 text-sm text-muted-foreground">You CAN say</p>
                <ul className="mt-5 space-y-3">
                  {approved.map((s) => (
                    <li
                      key={s}
                      className="flex gap-3 rounded-xl border-l-4 border-success bg-success/10 p-4 shadow-card"
                    >
                      <Check className="mt-0.5 size-5 shrink-0 text-success" aria-hidden="true" />
                      <span className="text-sm leading-relaxed">{s}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h2 className="flex items-center gap-2 text-xl font-bold">
                  <XCircle className="size-6 text-destructive" aria-hidden="true" />
                  Prohibited Statements
                </h2>
                <p className="mt-1 text-sm text-muted-foreground">You CANNOT say</p>
                <ul className="mt-5 space-y-3">
                  {prohibited.map((p) => (
                    <li
                      key={p.text}
                      className="flex gap-3 rounded-xl border-l-4 border-destructive bg-destructive/10 p-4 shadow-card"
                    >
                      <X className="mt-0.5 size-5 shrink-0 text-destructive" aria-hidden="true" />
                      <span className="text-sm leading-relaxed">
                        <span className="font-medium">"{p.text}"</span>
                        <span className="mt-1 block text-xs text-muted-foreground">
                          {p.reason}
                        </span>
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        </section>

        {/* Accordion */}
        <section className="border-y border-border bg-secondary/50 py-14 sm:py-20">
          <div className="mx-auto max-w-4xl px-4 sm:px-6">
            <h2 className="text-3xl font-bold tracking-tight text-balance">
              Detailed compliance guidance
            </h2>
            <Accordion
              type="single"
              collapsible
              defaultValue="income"
              className="mt-8 space-y-3"
            >
              {accordionSections.map((s) => (
                <AccordionItem
                  key={s.value}
                  value={s.value}
                  className="rounded-2xl border border-border bg-card px-5 shadow-card"
                >
                  <AccordionTrigger className="py-5 text-left text-base font-semibold hover:no-underline">
                    {s.title}
                  </AccordionTrigger>
                  <AccordionContent className="space-y-4 pb-5 text-sm leading-relaxed">
                    <p className="text-muted-foreground">{s.why}</p>
                    <div>
                      <h3 className="text-sm font-semibold">Rules</h3>
                      <ul className="mt-2 space-y-1.5">
                        {s.rules.map((r) => (
                          <li key={r} className="flex gap-2 text-muted-foreground">
                            <Check className="mt-0.5 size-4 shrink-0 text-success" aria-hidden="true" />
                            {r}
                          </li>
                        ))}
                      </ul>
                    </div>
                    <div>
                      <h3 className="text-sm font-semibold">What to say instead</h3>
                      <ul className="mt-2 space-y-1.5">
                        {s.instead.map((i) => (
                          <li key={i} className="text-muted-foreground">
                            {i}
                          </li>
                        ))}
                      </ul>
                    </div>
                    <div className="rounded-xl border-l-4 border-success bg-success/10 p-4">
                      <p className="text-xs font-semibold tracking-wide text-success uppercase">
                        Approved script
                      </p>
                      <p className="mt-1">{s.script}</p>
                    </div>
                  </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
          </div>
        </section>

        {/* Footer card */}
        <section className="py-14 sm:py-20">
          <div className="mx-auto max-w-4xl px-4 sm:px-6">
            <div className="rounded-2xl border border-border bg-card p-8 text-center shadow-card">
              <span className="mx-auto grid size-12 place-items-center rounded-2xl bg-accent text-accent-foreground">
                <Download className="size-6" aria-hidden="true" />
              </span>
              <Button
                className="mt-5 min-h-11 rounded-xl px-6"
                onClick={() => toast.success("Download ready!")}
              >
                <Download />
                Download full guidelines (PDF)
              </Button>
              <p className="mt-4 text-sm text-muted-foreground">Last updated: January 2026</p>
              <p className="mt-1 text-sm text-muted-foreground">
                Questions?{" "}
                <a href="mailto:compliance@uw.co.uk" className="text-primary hover:underline">
                  compliance@uw.co.uk
                </a>
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
