/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as TrainingIndexRouteImport } from './routes/training.index'
import { Route as TrainingModuleIdRouteImport } from './routes/training.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingModuleIdRoute = TrainingModuleIdRouteImport.update({
  id: '/training/$moduleId',
  path: '/training/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/trainer': typeof TrainerRoute
  '/training/$moduleId': typeof TrainingModuleIdRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/trainer': typeof TrainerRoute
  '/training/$moduleId': typeof TrainingModuleIdRoute
  '/training': typeof TrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/badges': typeof BadgesRoute
  '/dashboard': typeof DashboardRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/trainer': typeof TrainerRoute
  '/training/$moduleId': typeof TrainingModuleIdRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/badges'
    | '/dashboard'
    | '/guidelines'
    | '/login'
    | '/sessions'
    | '/settings'
    | '/signup'
    | '/trainer'
    | '/training/$moduleId'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/badges'
    | '/dashboard'
    | '/guidelines'
    | '/login'
    | '/sessions'
    | '/settings'
    | '/signup'
    | '/trainer'
    | '/training/$moduleId'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/badges'
    | '/dashboard'
    | '/guidelines'
    | '/login'
    | '/sessions'
    | '/settings'
    | '/signup'
    | '/trainer'
    | '/training/$moduleId'
    | '/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  BadgesRoute: typeof BadgesRoute
  DashboardRoute: typeof DashboardRoute
  GuidelinesRoute: typeof GuidelinesRoute
  LoginRoute: typeof LoginRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TrainerRoute: typeof TrainerRoute
  TrainingModuleIdRoute: typeof TrainingModuleIdRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$moduleId': {
      id: '/training/$moduleId'
      path: '/training/$moduleId'
      fullPath: '/training/$moduleId'
      preLoaderRoute: typeof TrainingModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  BadgesRoute: BadgesRoute,
  DashboardRoute: DashboardRoute,
  GuidelinesRoute: GuidelinesRoute,
  LoginRoute: LoginRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TrainerRoute: TrainerRoute,
  TrainingModuleIdRoute: TrainingModuleIdRoute,
  TrainingIndexRoute: TrainingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
